before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPMAUTH}" > .npmrc
  - echo "//registry.npmjs.org/:_password=\${NPMTOKEN}" >> .npmrc
  - echo "//registry.npmjs.org/:username=lccgov" >> .npmrc
  - echo "//registry.npmjs.org/:email=developer@leeds.gov.uk" >> .npmrc
  - npm install -g npm@latest
  - npm --version
  - node -v
install: 
script:
- chmod +x ./bin/publish.sh
- "./bin/publish.sh"
env:
  global:
 - secure: doLWxFyhNTY2T69GyXV/F/bq79MsSfrpxOBmxvq2PJWVneDkJ+edUkyckzIwEyyqn8WHIenZAQkLIxrpg/JQOKU3xc1RUo4Xco8T3u+6AioolTfyXzRsr5KeINZCaAfWFry+QipzYmFyjrMYMuqT746Tt08+swrK2QZxKGN5ndb8TR5bhy+yf+LLo1/JuPS8ylX9GpCxPLcHHDLa0pxObw+y096V0xbBeL6kkFE53DmeftlrTkbla3QgCzDxaux1aFuEifZ7RcPwPB65T6Yw9BzPrAw6E08jDNiAtHWzrF7EbVdek4GsSnQr1MqAhRBy5w4txihUQxDYclpxd0YsmLnG6s0yLVVYrG+778J0kZwLecUfGpcpeOjQF/dZRTKOG2K8L5pVLp5zH+lqANfyscXJBU7zjV+merhIA/jXKBpkdIhqeV/skirtu2gJru6ObMIM5/qAiVVY4EDqkBvPgtbKuQ1w92K51jYH5tt34j0MqXdI8GEWe8Oea7KRxS6RYjKrFSl2gbRx5CeiOrvE6xCkgGAhOX5rk0Nx/4nQ4otkHdKMs3ijvdNgy23fx459cNNw467/ACLE1BOl8J5riXbIWsk6RrbjLSxU05ja20zbu/1v0SXOqKozhQtvgC6GquFK9MFpQwAfhB8OjW4Q2mTRKMD+su691XMht1t0ZgE=
 - secure: XPMgpaaNZcMXPh/XVpwM+LRYQnWNq+vnfCFz+rFQtmZn5vUl9FD3xWkVx7AHiAvWi/hGPUi+OUbDkp58vL2aOHZI7nhM+Q7fJKfTL0XehxYTKRmOJH1lu2eSW4FmDK68G6//Geu4s0DssDllBPC9u904qGociC5tMoD53NaRVPLzy5OZDaOH77lqPqCllcOGVzstnB4MIEMPgO4/s1oxwnqu4wfhcltf35eVtmIQ5++NbIi5jgJROPCCbDGnXsfBwbNFnEFMLSXz0G1pXMEGDTvfY7ZYI2VD6uixRgO+FDVPE5G1vTwWEIo7ccUG0VdFGU/miWcP1LRYpN0da0DEzxlFNEyXWT4f4b8YZAj1G+oNSW5Yvm2/+fKkoX3aceRnAKJqwBd7Lro2sLs4tyVsnUjQLWGllGRzyddYEQC/HiPp5h+UTWhTMeAgtFt9K2XB9FCE5Nl+zSXzAnNcPhM1cWSfiwzpcESnx88MrMSIEXvwVALDEvOu8siTT4tIrs7bW7AnGWB5FF0im1riMMUrMNI2EpM9g7dXdFnKk6EdmrVBlZxPuWlhCrc8Ja6vzHaAlJR7NIGAMgXc7/Ba6Cv1hqADotIxAWlGbkHPo4nTBgFL/eaWnbds9/iDobggulsoHb8M8WelUvS/80w4gbBvoeJAq9/takhstG0JHGNYL0w=
 - secure: pCZB+HHIjTwus+3qadBTqcYqK1LlqdU8lisslS516GX23Dw0i1jnpB9oSAlEbaMYBynuwZBqDJSUtNJvLAUpr9hJPQai4YkDYy7enWMDu/w2sORsUL/IKKI3VUkVwAy1GkAz167WeI/h2H2GGouV6iQyOje2+5zuSiam4Dsk6LfOdQ6643DPv6q1Dfne8+cyJq81PUz1lJHUO2HK6KqISVQOl8UAKBoVhOJDuufjxtE3Lsrrqr43qqijf4FpqyM4YjwCgYziRusqvV7kY35lnzie+W7oK8SUsUydtGG3y+wLuD78z+SZEbn35helyDGrYFI/9doEq25RpYtXPsdNcCOHQvvSog93LkD5C2dkkwGfwdugABsVG3wVHBR1ON1RPecJ9aCEE6axq5Qb1Ynl1zilHJj6qbSbKVjTTnRPQH3B8QkSg4DlKldxNYPM30XvoxvWFtw28LxwSX56130eFceMt80sljwq0SV84z4q9cbnlKa5O9t8CGc2jJZiUYO0ugmcprWZgG5wPM2r3LxvVvgcWX75c6N3hNK2VIg7/vtVOFdSwk8M2VYy6KZKQAiOMnG7M6vfforLw5YvAIZpYKLTXCy724tIrXaGUthw4IBPm5SFoGxhfZ56LStwOLx6+3v0JtcRcIw20sWKW0jD4tlf56ZIwpp/Csy8uAB/bQg=
language: node_js
node_js:
- "6"



 

 

  

